### ISSUE TITLE
Uncaught TypeError: Array.concat is not a function

### ISSUE THREAD

**Issue by AleBles** [zac-garby/js13k#1]
I love this concept! But for me in Chrome it crashes because Array.concat is used :) should be Array.prototype.concat

https://github.com/zac-garby/js13k/blob/master/main.js#L397

**Comment by zac-garby** [comment]
Weird, it works for me in Firefox. I'll look into fixing that later :)

**Comment by end3r** [comment]
It was crashing on Linux, I've fixed this at https://js13kgames.com/games/datacenter/index.html already.
